### ISSUE TITLE
workflow not creationg pull request for new repo

### ISSUE THREAD

**Issue by mezalex2018** [zkoppert/advanced-security-enforcer#29]
![GHS](https://user-images.githubusercontent.com/37575739/154147756-85dde194-50ae-42bc-97c5-929fef683987.jpg)

**Comment by zkoppert** [comment]
Hi @mezalex2018! Thanks for using this github action!

The [printing of the repo name](https://github.com/zkoppert/advanced-security-enforcer/blob/main/enforcer.py#L44) as you have highlighted in the log happens in order to identify it found a repository that was created in the last 24 hours. This happens before the repo is checked to see if it contains code that is language compatible with the advanced security code scanning tool. Can you confirm that your repo contained code in [one of these languages](https://github.com/zkoppert/advanced-security-enforcer/blob/main/enforcer.py#L28-L38) when the action was ran?

**Comment by mezalex2018** [comment]
Hi Zack,

 

Nice to meet you,

 

Appreciate your quick response, you are right repo have no code inside, I am working in corporate environment and people asking for new repo’s and it can take a week before they start pushing code, I was wondering how to solve this problem, maybe you have any thought or were thinking about it

 

Thank you

**Comment by zkoppert** [comment]
Oh ok, that makes sense. One thing I can think of would be to change the time frame to something that matches with the expectations of when code would be present. So instead of searching for repos created in the last 24 hours, it could be switched to created in the last week.

Right now that value of [24 hours is hardcoded](https://github.com/zkoppert/advanced-security-enforcer/blob/main/enforcer.py#L24) (I wasn't thinking ahead 😅 ). I could make that a part of the [configuration file ](https://github.com/zkoppert/advanced-security-enforcer/blob/main/.env-example) instead of hardcoding it so that you can change it to any value you would like. How does that sound?

**Comment by mezalex2018** [comment]
Sounds amazing, it will help a lot,

 

Thank you very much 😊

**Comment by zkoppert** [comment]
@mezalex2018 The new version is now deployed. Hope that helps! Let me know if you run into any issues.

**Comment by mezalex2018** [comment]
Hi Zack,

 

Really appreciate your quick response 

 

Thank you
